export const GET_CARS_RESPONSE = 'GET_CARS_RESPONSE';
export const GET_CAR_RESPONSE = 'GET_CAR_RESPONSE';
export const ADD_NEW_CAR_RESPONSE = 'ADD_NEW_CAR_RESPONSE';
export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
